In [3]:
# [과제] 1변향 데이터 data에 대하여 평균,표본분산, 불편분산, 편차, 표준편차, 최대, 최소, 4분위수, 중앙값을 구하세요
# 단 함수를 사용하는 경우와 사용하지 않는 경우를 모두 수행
import numpy as np
import pandas as pd


In [72]:
# 함수 사용 없음
np.random.seed(0)
arr = np.random.randint(0,100,20)
print(arr)
print(arr[0:3])
#평균
mean = np.sum(arr)/len(arr)
print('mean',mean)
#편차
dev = arr-mean
print('편차',dev)
#표본분산
var1 = np.mean(dev**2)
print('표본분산',var1)
#불편분산
var2 = (np.sum(dev**2))/(len(arr)-1)
print('불편분산',var2)
# 표준편차
print('표준편차')
# 표본분산의 표준편차
nv1 = np.sqrt(var1)
print('표본분산의 표준편차',nv1)
# 불편분산의 표준편차
nv2 = np.sqrt(var2)
print('불편분산의 표준편차',nv2)
arr_sort = np.sort(arr)
# 최대값
print('최대값',arr_sort[-1])

#최소값
print('최소값',arr_sort[0])

# 중앙값
a = arr_sort[len(arr_sort)//2]
if len(arr_sort)%2 ==0:
    b = arr_sort[len(arr_sort)//2-1]
    print('중앙값', (a+b)/2)
else:
    print('중앙값', a)
# 4분위수

#1사분위
a = arr_sort[len(arr_sort)//4]
if len(arr_sort)%4 ==0:
    b = arr_sort[len(arr_sort)//4-1]
    print('1사분위', (3*a+b)/4)
else:
    print('1사분위', a)
#3사분위
a = arr_sort[len(arr_sort)//4*3]
if len(arr_sort)%4 ==0:
    b = arr_sort[len(arr_sort)//4*3-1]
    print('3사분위', (a+3*b)/4)
else:
    print('3사분위', a)

[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
[44 47 64]
mean 58.3
편차 [-14.3 -11.3   5.7   8.7   8.7 -49.3  24.7 -37.3 -22.3  28.7  11.7  29.7
  29.7 -46.3  -0.3   6.7 -19.3  28.7 -12.3  29.7]
표본분산 629.41
불편분산 662.5368421052631
표준편차
표본분산의 표준편차 25.088044961694404
불편분산의 표준편차 25.739791026837477
최대값 88
최소값 9
중앙값 64.5
1사분위 42.75
3사분위 84.0


In [73]:
#  함수 사용 버전
mean = arr.mean()
print('평균', mean)
dev = arr-arr.mean()
print('편차',dev)
var1 = np.var(arr,ddof = 0)
print('표본분산', var1)
var2 = np.var(arr,ddof=1)
print('불편분산', var2)
print('표준편차')
std1 = np.std(arr,ddof=0)
print('표본분산의 표준편차',std1)
std2 = np.std(arr,ddof=1)
print('불편분산의 표준편차',std2)
maxvalue = np.max(arr)
print('최대값',maxvalue)
minvalue = np.min(arr)
print('최소값',minvalue)
q50 = np.percentile(arr,50)
print('중앙값',q50)
q25 = np.percentile(arr,25)
print('1사분위',q25)
q75 = np.percentile(arr,75)
print('3사분위',q75)

평균 58.3
편차 [-14.3 -11.3   5.7   8.7   8.7 -49.3  24.7 -37.3 -22.3  28.7  11.7  29.7
  29.7 -46.3  -0.3   6.7 -19.3  28.7 -12.3  29.7]
표본분산 629.41
불편분산 662.5368421052631
표준편차
표본분산의 표준편차 25.088044961694404
불편분산의 표준편차 25.739791026837477
최대값 88
최소값 9
중앙값 64.5
1사분위 42.75
3사분위 84.0


In [74]:
# 검증
df = pd.Series(arr)
df.describe()

count    20.000000
mean     58.300000
std      25.739791
min       9.000000
25%      42.750000
50%      64.500000
75%      84.000000
max      88.000000
dtype: float64

In [ ]:
#과제 10행 2열 2차원의 배열을 생성하고 두 열간의 공분산, 상관계수를 구하세요(단, numpy, pandas 두가지 방식

In [110]:
# np 사용
np.random.seed(10)
arr2 = np.random.randint(50,100,20).reshape(10,2)
print(arr2)
print(arr2[:,0])
print(arr2[:,1])
# 공분산
cov_mat = np.cov(arr2[:,0],arr2[:,1],ddof=0)
print(cov_mat)
print('공분산',cov_mat[0][1])
# 상관계수
print('상관계수')
print(np.corrcoef(arr2[:,0],arr2[:,1])[0][1])

[[59 86]
 [65 50]
 [99 78]
 [75 79]
 [98 79]
 [99 58]
 [59 50]
 [92 90]
 [86 66]
 [86 97]]
[59 65 99 75 98 99 59 92 86 86]
[86 50 78 79 79 58 50 90 66 97]
[[236.16  74.36]
 [ 74.36 246.21]]
공분산 74.36
상관계수
0.3083779854313548


In [115]:
# df 사용
df = pd.DataFrame(arr2)
display(df)
cov_mat = np.cov(df[0],df[1],ddof=0)
print('공분산',cov_mat[0][1])
df.corr()

0   1
0  59  86
1  65  50
2  99  78
3  75  79
4  98  79
5  99  58
6  59  50
7  92  90
8  86  66
9  86  97

공분산 74.36


0         1
0  1.000000  0.308378
1  0.308378  1.000000