In [4]:
import numpy as np

arr = np.random.randint(1,10,size=(5,5))
print(arr)
print(arr.T)
print(np.transpose(arr))

[[9 4 2 6 9]
 [6 1 5 3 6]
 [1 2 1 6 9]
 [1 6 9 4 4]
 [5 3 4 3 8]]
[[9 6 1 1 5]
 [4 1 2 6 3]
 [2 5 1 9 4]
 [6 3 6 4 3]
 [9 6 9 4 8]]
[[9 6 1 1 5]
 [4 1 2 6 3]
 [2 5 1 9 4]
 [6 3 6 4 3]
 [9 6 9 4 8]]


In [5]:
#행렬곱 내적

np.dot(arr.T,arr)

array([[144,  65,  78,  97, 170],
       [ 65,  66,  81,  72, 108],
       [ 78,  81, 127,  81, 125],
       [ 97,  72,  81, 106, 166],
       [170, 108, 125, 166, 278]])

In [11]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

y=np.swapaxes(a,0,1) #0은 2차원 (열), 1은 1차원(행)
print(y,'\n')
print(np.transpose(a))
print(a.T)

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


In [ ]:
1~100을 아래와 같이 출력하세요

In [39]:
a = np.arange(1,101).reshape(10,10)
a[[1,3,5,7,9]]=a[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [29]:
a = np.arange(1, 101).reshape((10, -1))

for i in range(10):
    if i % 2 == 1:
        a[i] = a[i][::-1]

print(a)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [41]:
#(0,1,2)
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) > (2,1,3)
a = np.arange(6).reshape(1,2,3)
print(a,'\n')

y = np.transpose(a,(1,0,2))
print(y,y.shape,'\n')

[[[0 1 2]
  [3 4 5]]] 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3) 



In [43]:
# (1,2,3 ) > (2,3,1)
y = np.transpose(a,(1,2,0))
print(y,y.shape)

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [45]:
# 나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

[1 2 0]
[1 2 0]


In [49]:
# 각 수의 역수를 구해주는 함수
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value))

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1,dtype=float))

[1.17647059 0.54054054 1.         0.01      ]
[100] 

[0.01]


In [50]:
#승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

[  4 100 225] 

[   2  100 3375]


In [52]:
arr = np.random.randn(10)
print(arr.mean(),'\n')
print(arr.std())

0.2789339557387111 

0.9584802189489389


In [53]:
# 양수인 원소의 개수

(arr>0).sum()

5

In [54]:
# 하나 이상의 값이 True인지 검사
bools = np.array([False, False,True,True])
bools.any()

True

In [55]:
# 모든 원소가 True인지 검사
bools.all()

False

In [62]:
# 삼항식의 벡터화 버전

arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr >0,2,-2)

[[ 1.59456936 -0.38304039  0.55951501  0.01746587]
 [-0.60137724 -0.50747082 -0.66172296  0.2274389 ]
 [ 0.47780875  0.0859228  -0.93643826 -1.8500661 ]
 [ 0.02606071  0.27462932 -0.35030403 -0.36283331]] 



array([[ 2, -2,  2,  2],
       [-2, -2, -2,  2],
       [ 2,  2, -2, -2],
       [ 2,  2, -2, -2]])

In [63]:
np.where(arr>0,2,arr)

array([[ 2.        , -0.38304039,  2.        ,  2.        ],
       [-0.60137724, -0.50747082, -0.66172296,  2.        ],
       [ 2.        ,  2.        , -0.93643826, -1.8500661 ],
       [ 2.        ,  2.        , -0.35030403, -0.36283331]])

In [66]:
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y)짝을 만들수 있는 2차원 배열 반환
# meshgrid

x = np.arange(1,4)
y = np.arange(1,4)
xs, ys = np.meshgrid(x,y)
print(xs,'\n',ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]


In [72]:
#np.sort()
arr = np.random.randint(1,100,size=10)
arr = np.sort(arr)
print(arr,'\n')

[ 2 14 15 16 20 61 61 61 73 87] 



In [76]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행,열 방향으로 정렬 수행

arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_arr2d_axis0 = np.sort(arr2d,axis = 0)
print(sort_arr2d_axis0,'\n')
sort_arr2d_axis1 = np.sort(arr2d,axis = 1)
print(sort_arr2d_axis1)

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [81]:
# ndarray.sort() : 원본 반영

arr = np.random.randint(1,10,size=10)
print(arr,'\n')
arr.sort()
print(arr,'\n')

[4 3 8 2 1 3 9 1 9 3] 

[1 1 2 3 3 3 4 8 9 9] 



In [88]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
# 행방향 0 열방향 1
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort()
print(arr)

[[7 2 1]
 [7 3 8]
 [3 2 1]
 [2 8 7]
 [6 8 5]] 

[[1 2 7]
 [3 7 8]
 [1 2 3]
 [2 7 8]
 [5 6 8]]


In [89]:
#정렬된 행렬이 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때

org_array = np.array([3,1,9,5])

sort_indices =np.argsort(org_array)
print(org_array)
print(sort_indices)

[3 1 9 5]
[1 0 3 2]


In [92]:
# 배열에서 정렬한 후 5%내 분위수 요소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[:int(0.05*len(large_arr))]

array([-3.05516786, -2.96816695, -2.93537598, -2.81608229, -2.58332414,
       -2.56567652, -2.55691944, -2.42606481, -2.41239686, -2.39657832,
       -2.37808663, -2.34266459, -2.31691957, -2.27959813, -2.27639421,
       -2.19839785, -2.19450182, -2.1441345 , -2.10478624, -2.08886733,
       -2.0591665 , -2.05633332, -2.00418427, -1.99521925, -1.98169274,
       -1.95910912, -1.9532633 , -1.94673067, -1.91895174, -1.91681259,
       -1.8837067 , -1.87747408, -1.87603335, -1.8706297 , -1.86715523,
       -1.86535419, -1.86055432, -1.84999115, -1.82475519, -1.82178417,
       -1.80635741, -1.78661759, -1.78549163, -1.76689098, -1.75484844,
       -1.74397222, -1.74161663, -1.72766118, -1.72687075, -1.71714223])

In [93]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [100]:
uni = np.array(list(set(names)))
sorted(uni)

['Bob', 'Joe', 'Will']

In [101]:
# 첫번째 배열의 원소가 두번째 배열에 포함하는지 알려주는 boolean 배열 반환

values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [102]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식으로 입출력 실행 .npy파일로 저장

arr = np.arange(10)
np.save('some_array',arr)

In [103]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장 .npz파일로 저장
np.savez('array_archive.npz',a=arr,b=arr)

In [106]:
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
# 인덱싱을 사용하여 [1 0 1 0 1 0 1 0]을 출력하세요

a = np.ones(10,dtype=int)
index = np.argsort(a)
print(np.where(index%2!=0,0,a))

[1 0 1 0 1 0 1 0 1 0]


In [118]:
a = np.arange(10)
print(a)
print(a[6:])

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [153]:
print(np.argmin(a))
print(np.argmax(a))

0
9


In [152]:
print(np.argsort(a)[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [155]:
x = np.ones((10,10))
x[1:9,1:9] = 0
print(x)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


[파이썬 랜덤 함수]

In [305]:
import random
print(random.random(),'\n') # 0.0~1.0 사이의 숫자를 랜덤하게 뽑음
print(random.randint(1,10),'\n') # 1~10 사이 정수 중에서 난수값 리턴
print(random.uniform(10,20),'\n') # min max 사이 float 리턴
print(random.randrange(10),'\n') # 0~10 사이 int값 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부요소 중 하나를 랜덤하게 뽑음
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') #리스트 내 요소를 중복없이 지정한 수만큼 리턴
random.shuffle(li)
print(li,'\n') #리스트 내 요소를 무작위로 섞어서 정렬 후 리턴

0.8690415319664742 

6 

19.67964972969783 

5 

3 

[4, 1, 5] 

[5, 3, 1, 4, 2] 



.[numpy random 함수].

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 균일 분로의 정수형 난수 1개 생성
- np.random.rand : 0부터 1 사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [309]:
print(np.random.randint(6),'\n') # 0 ~ 5까지 정수인 난수 한개 생성
print(np.random.randint(1,20),'\n') #1 ~ 19까지 정수인 난수 한개 생성
print(np.random.randint(10,size = 10),'\n') # 0~10에서 10개 생성
print(np.random.randint(10,20,size = 10),'\n') #10 ~20 사이에서 10개 생성
print(np.random.randint(10,20,size = (3,5))) # 10~20 사이 난수로 배열 3행 5열 채움

5 

9 

[1 3 4 5 1 8 0 4 1 3] 

[15 14 12 11 13 13 17 12 18 14] 

[[19 17 10 14 17]
 [10 19 17 17 10]
 [16 12 18 14 10]]


In [312]:
r = np.random.rand(6)
print(r,'\n') # 0~1사이의 균일 분포
print(r.mean())

[0.16794145 0.52834952 0.08447296 0.75254284 0.08897003 0.59937038] 

0.37027453114657716


In [320]:
# 표준 정규분포

r = np.random.randn(1000)
r.mean()

-0.019418529852644133

In [321]:
list = np.arange(1,6)
np.random.shuffle(list)
list

array([5, 1, 2, 3, 4])

In [334]:
np.random.choice(list)

5

In [335]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts = True)
print(index)
print(count)

[ 2  3  7 11]
[3 2 1 2]


In [336]:
np.random.uniform(1.0, 2.0, 10)

array([1.5428217 , 1.83567757, 1.63455175, 1.69659036, 1.41271335,
       1.73915675, 1.82366761, 1.46498795, 1.73223465, 1.69551644])

In [337]:
# 0 ~ 1 사이의 실수값들로 난수 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0, 1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.76698273, 0.43979355, 0.4931054 ],
       [0.95505041, 0.29442868, 0.8914094 ]])

In [338]:
!pip install pandas

In [341]:
ar = np.random.rand(4,8)
ar

array([[0.63462448, 0.36769445, 0.82277324, 0.08659701, 0.07857764,
        0.48624028, 0.4586331 , 0.57802519],
       [0.42936458, 0.4883043 , 0.63079643, 0.79229888, 0.55574366,
        0.05648699, 0.21083867, 0.10172455],
       [0.53705851, 0.87777921, 0.88212159, 0.88184371, 0.64118668,
        0.50662197, 0.51331055, 0.47946941],
       [0.9173426 , 0.00745237, 0.37832007, 0.93997248, 0.39547419,
        0.71298311, 0.78688102, 0.54197489]])

In [342]:
# 배열을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
df

0         1         2         3         4         5         6  \
0  0.634624  0.367694  0.822773  0.086597  0.078578  0.486240  0.458633   
1  0.429365  0.488304  0.630796  0.792299  0.555744  0.056487  0.210839   
2  0.537059  0.877779  0.882122  0.881844  0.641187  0.506622  0.513311   
3  0.917343  0.007452  0.378320  0.939972  0.395474  0.712983  0.786881   

          7  
0  0.578025  
1  0.101725  
2  0.479469  
3  0.541975

In [343]:
print(df[0])
type(df[0])

0    0.634624
1    0.429365
2    0.537059
3    0.917343
Name: 0, dtype: float64


pandas.core.series.Series

In [346]:
columns = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

id    gender       age    region   product     price       qty  \
0  0.634624  0.367694  0.822773  0.086597  0.078578  0.486240  0.458633   
1  0.429365  0.488304  0.630796  0.792299  0.555744  0.056487  0.210839   
2  0.537059  0.877779  0.882122  0.881844  0.641187  0.506622  0.513311   
3  0.917343  0.007452  0.378320  0.939972  0.395474  0.712983  0.786881   

       time  
0  0.578025  
1  0.101725  
2  0.479469  
3  0.541975

In [436]:
# id, gender,age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력하세요
arr1 = np.zeros((4,3),dtype = int)
arr1[:,0] =np.random.randint(10000,99999,size =4)
arr1[:,1] =np.random.choice([0,1],4)
arr1[:,2] =np.random.randint(1,100,size =4)
print(arr1)
index = [np.arange(4)]
columns = ['id','gender','age']
df = pd.DataFrame(arr1,index,columns = columns)
df

[[63802     0    71]
 [91757     1     3]
 [30721     0    36]
 [97033     1    28]]


id  gender  age
0  63802       0   71
1  91757       1    3
2  30721       0   36
3  97033       1   28

In [398]:
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df


ID Gender Age
1  1693      F  21
2  6066      M  21
3  1625      M  11