In [10]:
# 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
import numpy as np
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')
np.transpose(arr,(1,0,2))
print(arr,arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [38]:
     ([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

x = np.ones((5,5),dtype = int)
y = np.zeros((9,9), dtype = int)
y[2:7,2:7] = x
print(y)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [19]:
b= np.array([[0,1],[1,0]])
b = np.tile(b,(4,4))
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [37]:
c = np.zeros((8,8),dtype=int)
for i in range(8):
    for j in range(8):
        if (i+j)%2 ==1:
            c[i,j] = 1
            
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [39]:
d = np.arange(336).reshape(6,7,8)
for i in range(6):
    for j in range(7):
        for k in range(8):
            if d[i,j,k] == 100:
                print(i,j,k)

1 5 4


In [36]:
e = np.arange(4)+1
print(e)
array = np.zeros((5,5),dtype = int)
for i in e:
    array[i,i-1] = i
    
print(array)

[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [72]:
#  고객 구매 데이터 생성 및 데이터프레임으로 출력 관측치 1000
# id 1~1000 일련번호
# gender : 0,1 난수
# age :0~80 사이 정수 난수
# product_19,product_20 11111~99999
#price_19,price20 1000~50000 실수 난수
# quantity_19, quantity_20 1~100 정수 난수
#time_19, time_20 1~14 사이 정수 난수 생성
#amount_19,amount-20 price*quantity
#sales 19년 대비 증가는 1, 감소 및 무변화는 0

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(11111,100000,size = customer)
df.product_20 = np.random.randint(11111,100000,size = customer)
pricearray= np.random.randint(1000,50001,size = 100000)

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

df

id gender  age  product_19  product_20  price_19  price_20  \
1        1      M   40       24227       55976      3335     38196   
2        2      F   29       77462       78920      5437     38011   
3        3      F   25       53750       46507      2280     33039   
4        4      M   19       73611       29381     25557     21295   
5        5      F   68       82728       84075     31101      8633   
...    ...    ...  ...         ...         ...       ...       ...   
996    996      M   24       73435       97517     37768     18645   
997    997      M   53       36781       83820     42314     15761   
998    998      M   24       38495       96299      6562     27294   
999    999      F   73       56675       61737     25790     19203   
1000  1000      M   42       88153       76382     15593     43085   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              21            7        8        7      70035     267372      1  
2              76           65        8       17     413212    2470715      1  
3              88           51       24        2     200640    1684989      1  
4              47            2       11       13    1201179      42590      0  
5              14           82       13        7     435414     707906      1  
...           ...          ...      ...      ...        ...        ...    ...  
996            87           32       11       21    3285816     596640      0  
997            41           55        5       15    1734874     866855      0  
998            97           16       10       23     636514     436704      0  
999             7           93       22       18     180530    1785879      1  
1000            9           10        4       19     140337     430850      1  

[1000 rows x 14 columns]