In [10]:
# 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
import numpy as np
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')
np.transpose(arr,(1,0,2))
print(arr,arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [38]:
     ([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

x = np.ones((5,5),dtype = int)
y = np.zeros((9,9), dtype = int)
y[2:7,2:7] = x
print(y)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [19]:
b= np.array([[0,1],[1,0]])
b = np.tile(b,(4,4))
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [37]:
c = np.zeros((8,8),dtype=int)
for i in range(8):
    for j in range(8):
        if (i+j)%2 ==1:
            c[i,j] = 1
            
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [39]:
d = np.arange(336).reshape(6,7,8)
for i in range(6):
    for j in range(7):
        for k in range(8):
            if d[i,j,k] == 100:
                print(i,j,k)

1 5 4


In [36]:
e = np.arange(4)+1
print(e)
array = np.zeros((5,5),dtype = int)
for i in e:
    array[i,i-1] = i
    
print(array)

[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [76]:
#  고객 구매 데이터 생성 및 데이터프레임으로 출력 관측치 1000
# id 1~1000 일련번호
# gender : 0,1 난수
# age :0~80 사이 정수 난수
# product_19,product_20 11111~99999
#price_19,price20 1000~50000 실수 난수
# quantity_19, quantity_20 1~100 정수 난수
#time_19, time_20 1~14 사이 정수 난수 생성
#amount_19,amount-20 price*quantity
#sales 19년 대비 증가는 1, 감소 및 무변화는 0

import numpy as np
import pandas as pd
#import warnings
#warnings.filterwarnings('ignore')

customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(11111,100000,size = customer)
df.product_20 = np.random.randint(11111,100000,size = customer)
pricearray= np.random.randint(10,500,size = 100000)*100

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

df

id gender  age  product_19  product_20  price_19  price_20  \
1        1      M   40       24227       55976     42900     17000   
2        2      F   29       77462       78920     27400     38500   
3        3      F   25       53750       46507     25600     49500   
4        4      M   19       73611       29381     28000     19100   
5        5      F   68       82728       84075      1300     23200   
...    ...    ...  ...         ...         ...       ...       ...   
996    996      M   24       73435       97517      6400     21300   
997    997      M   53       36781       83820     34400     21600   
998    998      M   24       38495       96299     12700      7700   
999    999      F   73       56675       61737     15700     21000   
1000  1000      M   42       88153       76382     10100     32500   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              76           79       18       20    3260400    1343000      0  
2              66           45        4       19    1808400    1732500      0  
3              55           36       24       18    1408000    1782000      1  
4              71           15        2       17    1988000     286500      0  
5              20           90        3       20      26000    2088000      1  
...           ...          ...      ...      ...        ...        ...    ...  
996             7           76       20       10      44800    1618800      1  
997            28           53       10       24     963200    1144800      1  
998            72           35        8        7     914400     269500      0  
999            54            6        1       17     847800     126000      0  
1000           56           39       13       23     565600    1267500      1  

[1000 rows x 14 columns]