In [5]:
#zeros_like, ones_like, full_like 함수 예시
import numpy as np

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,0],[1,3,5,7,9],[2,4,6,8,0]])

arr2 = np.zeros_like(arr1)
arr3 = np.ones_like(arr1)
arr4 = np.full_like(arr1,7)
print(arr2,'\n',arr3,'\n',arr4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 
 [[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [8]:
arr11 = np.arange(1,101)
print(arr11[arr11%3==0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [10]:
arr12 = np.arange(1,101)
print(arr12[(arr12 %2 ==0) & (arr12%5==0)])

[ 10  20  30  40  50  60  70  80  90 100]


In [16]:
arr13 = np.random.randn(5,5)
print(arr13.mean().round(4))
print(arr13.var().round(4))

0.0386
0.7127


In [27]:
print(np.__version__)

1.21.2


In [29]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [31]:
arr14 = np.zeros(10,)
arr14[4] +=1
print(arr14)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [47]:
arr15 = np.arange(10,)
print(arr15[-1::-1])

[9 8 7 6 5 4 3 2 1 0]


In [51]:
arr16 = np.array([1,2,0,0,4,0])
print(arr16[arr16>0])

[1 2 4]
