In [5]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([[1,2],[3,4]])
array3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array1,type(array1),array1.shape)
print(array2,type(array2),array2.shape)
print(array3,type(array3),array3.shape)

[1 2 3] <class 'numpy.ndarray'> (3,)
[[1 2]
 [3 4]] <class 'numpy.ndarray'> (2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] <class 'numpy.ndarray'> (2, 2, 2)


In [6]:
array_int = np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float.dtype)
array_int2 = array_float.astype('int32')
print(array_int2.dtype)

float64
int32


In [8]:
zero_array =np.zeros((3,2),dtype=int)
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [10]:
one_array = np.ones((3,2))
print(one_array,one_array.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64


In [13]:
# reshape
ar1 = np.arange(10)
ar11 = ar1.reshape((2,5))
print(ar11,ar11.shape)
ar22 = ar1.reshape((2,1,5))
print(ar22,ar22.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]] (2, 1, 5)


In [15]:
ar33 = ar1.reshape((1,1,-1))
print(ar33,ar33.shape)

[[[0 1 2 3 4 5 6 7 8 9]]] (1, 1, 10)


In [20]:
ar3 = np.arange(8).reshape((2,2,2))
ar31 = ar3.reshape((-1))
print(ar31,ar31.shape)
ar32 = ar3.reshape((2,4))
print(ar32,ar32.shape)

[0 1 2 3 4 5 6 7] (8,)
[[0 1 2 3]
 [4 5 6 7]] (2, 4)


In [23]:
# indexing
ar1 = np.arange(1,10)
print(ar1)
value = ar1[1]
print(value)
print(ar1[-1])
print(ar1[-3])

[1 2 3 4 5 6 7 8 9]
2
9
7


In [29]:
ar2d = np.arange(1,10).reshape(3,3)
print(ar2d)
print(ar2d[0,0])
print(ar2d[0:2,3:0:-1])
print(ar2d[0:-1,0:-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[[3 2]
 [6 5]]
[[1 2]
 [4 5]]


In [35]:
ar1 = np.arange(1,20)
print(ar1)
print(ar1[3:6])
print(ar1[-4:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6]
[16 17 18]


In [45]:
ar2d = np.arange(1,10).reshape(3,3)
print(ar2d)
print(ar2d[0:2,0:2])
print(ar2d[1:3,:])
print(ar2d[-2:,:])
print(ar2d[0:2,1:3])
print(ar2d[:2,1:])
print(ar2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]
[1 4]


In [48]:
# boolean indexing
ar1 = np.arange(1,10)
print(ar1)
print(ar1[ar1>5])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [57]:
#fancy indexing
ar1 = np.arange(1,10).reshape(3,3)
print(ar1)
print(ar1[[0,1],2])
print(ar1[[0,1],:2])
print(ar1[[0,1],:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [66]:
#np.sort() : 원본 미반영
ar = np.array([3,1,9,5])
print(ar)
print(np.sort(ar))
#ndarray.sort() : 원본 반영
sort_ar1 = ar.sort()
print(sort_ar1)
print(ar)

[3 1 9 5]
[1 3 5 9]
None
[1 3 5 9]


In [68]:
# 내림차순 정렬
sort_ar_desc = np.sort(ar)[::-1]
print(sort_ar_desc)

[9 5 3 1]


In [69]:
ar2 = np.array([[8,12],[7,1]])
print(ar2)
sort_ar2_axis0 = np.sort(ar2,axis=0)
print(sort_ar2_axis0)
sort_ar2_axis1 = np.sort(ar2,axis=1)
print(sort_ar2_axis1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [70]:
# 정렬 행렬의 인덱스 반환
ar = np.array([3,1,9,5])
sort_indices = np.argsort(ar)
print(sort_indices)

[1 0 3 2]


In [71]:
# 행렬 내적
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[9,10],[11,12]])

np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [73]:
# 전치 행렬
a = np.array([[1,2],[3,4]])
a.transpose()

array([[1, 3],
       [2, 4]])